- hosts: all
  user: ubuntu
  become: yes
  gather_facts: false

  pre_tasks:
    - name: Install Python 2 for ansible
      raw: sudo apt-get -y install python

  tasks:


  roles:
  #  - python
     - nodejs
     - app
     - nginx 

